--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/CzechPMDevs/ImageOnMap
build-by-default: true
branches:
- main
projects:
  ImageOnMap:
    path: ""
    lint:
      syntaxError: false
    
...
